## Clean Speech 
<audio controls autoplay>
 <source src="audio/clean_TMHINT_01_01.wav"  type="audio/wav">
</audio>

## Noisy Speech
#### Four noise types artificially added. 

- car
<br>
<audio controls autoplay>
 <source src="audio/car_TMHINT_01_01.wav"  type="audio/wav">
</audio>

- engine
<br>
<audio controls autoplay>
 <source src="audio/engine_TMHINT_01_01.wav"  type="audio/wav">
</audio>

- street noise
<br>
<audio controls autoplay>
 <source src="audio/street_TMHINT_01_01.wav"  type="audio/wav">
</audio>

- background talkers
<br>
<audio controls autoplay>
 <source src="audio/talk_TMHINT_01_01.wav"  type="audio/wav">
</audio>

## Speech Generation 
#### Generating speech with EPG signals only
<br>
<audio controls autoplay>
 <source src="audio/EPG_ONLY_0dB_TMHINT_01_01.wav"  type="audio/wav">
</audio>

#### Generating speech with EPG signals and noisy speech signals in early fusion mode
<br>
<audio controls autoplay>
 <source src="audio/sg_EF_0dB_TMHINT_01_01.wav"  type="audio/wav">
</audio>

#### Generating speech with EPG signals and noisy speech signals in late fusion mode
<br>
<audio controls autoplay>
 <source src="audio/sg_LF_0dB_TMHINT_01_01.wav"  type="audio/wav">
</audio>

## Speech Enhancement
#### Using audio signal only

- car
<br>
<audio controls autoplay>
 <source src="audio/baseline/car_0dB_TMHINT_01_01.wav"  type="audio/wav">
</audio>

- engine
<br>
<audio controls autoplay>
 <source src="audio/baseline/engine_0dB_TMHINT_01_01.wav"  type="audio/wav">
</audio>

- street noise
<br>
<audio controls autoplay>
 <source src="audio/baseline/street_0dB_TMHINT_01_01.wav"  type="audio/wav">
</audio>

- background talkers
<br>
<audio controls autoplay>
 <source src="audio/baseline/talker_0dB_TMHINT_01_01.wav"  type="audio/wav">
</audio>

#### Combining EPG and audio signal in early fusion 

- car
<br>
<audio controls autoplay>
 <source src="audio/EF/car_0dB_TMHINT_01_01.wav"  type="audio/wav">
</audio>

- engine
<br>
<audio controls autoplay>
 <source src="audio/EF/engine_0dB_TMHINT_01_01.wav"  type="audio/wav">
</audio>

- street noise
<br>
<audio controls autoplay>
 <source src="audio/EF/street_0dB_TMHINT_01_01.wav"  type="audio/wav">
</audio>

- background talkers
<br>
<audio controls autoplay>
 <source src="audio/EF/talker_0dB_TMHINT_01_01.wav"  type="audio/wav">
</audio>

#### Combining EPG and audio signal in late fusion 

- car
<br>
<audio controls autoplay>
 <source src="audio/lF/car_0dB_TMHINT_01_01.wav"  type="audio/wav">
</audio>

- engine
<br>
<audio controls autoplay>
 <source src="audio/LF/engine_0dB_TMHINT_01_01.wav"  type="audio/wav">
</audio>

- street noise
<br>
<audio controls autoplay>
 <source src="audio/LF/street_0dB_TMHINT_01_01.wav"  type="audio/wav">
</audio>

- background talkers
<br>
<audio controls autoplay>
 <source src="audio/LF/talker_0dB_TMHINT_01_01.wav"  type="audio/wav">
</audio>

## Appendix
Appendix I. Comparison of different speech enhancement approach (p-value)
|       | Noisy - Baseline | Baseline - EF | Baseline - LF | EF - LF |
|-------|----------------|-------------|-------------|-------|
| PESQ  | 0.000          | 0.000       | 0.007       | 0.189 |
| STOI  | 0.000          | 0.000       | 0.000       | 0.842 |
| ESTOI | 0.000          | 0.000       | 0.000       | 0.585 |
| MCD   | 0.000          | 0.000       | 0.000       | 0.000 |
| SSNR  | 0.000          | 0.061       | 0.000       | 0.073 |

<br>

Appendix II. Comparison of noisy speech and baseleine in speech enhancement at SNR levels (p-values) 
|     |PESQ | STOI|ESTOI|  MCD| SSNR|
|-----|-----|-----|-----|-----|-----|
| 10dB|0.000|0.000|0.000|0.000|0.000|
|  5dB|0.000|0.000|0.000|0.000|0.000|
|  0dB|0.000|0.000|0.000|0.000|0.000|
| -5dB|0.000|0.000|0.000|0.000|0.000|
|-10dB|0.000|0.000|0.000|0.000|0.000|

<br>

Appendix III. Comparison of EF and LF in speech enhancement at SNR levels (p-values) 
|     |PESQ | STOI|ESTOI|  MCD| SSNR|
|-----|-----|-----|-----|-----|-----|
| 10dB|0.000|0.227|0.019|0.355|0.125|
|  5dB|0.008|0.406|0.117|0.018|0.687|
|  0dB|0.240|0.586|0.866|0.001|0.043|
| -5dB|0.909|0.758|0.118|0.000|0.001|
|-10dB|0.127|0.018|0.000|0.000|0.001|

